# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Routine.create!([
  { :ejercicio1 => "Primer ejercicio de la primer rutina", :ejercicio2 => "Segundo ejercicio de la primer rutina", :ejercicio3 => "Tercer ejercicio de la primer rutina", :created_at => "2013-12-16 00:55:54", :updated_at => "2013-12-16 02:06:48" },
  { :ejercicio1 => "Primer ejercicio de la tercer rutina", :ejercicio2 => "Segundo ejercicio de la tercer rutina", :ejercicio3 => "Tercer  ejercicio de la tercer rutina", :created_at => "2013-12-16 01:35:17", :updated_at => "2013-12-16 02:06:20" }
])


